// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPaymentStatus(arg1:string):Promise<boolean>;

export function GetDataDir():Promise<string>;

export function GetLiveViewURL():Promise<string>;

export function PrintPhoto(arg1:string):Promise<void>;

export function ProcessComposite(arg1:Array<string>,arg2:string,arg3:string):Promise<string>;

export function SaveWebRTCImage(arg1:string,arg2:number,arg3:string):Promise<string>;

export function SendEmail(arg1:string,arg2:string):Promise<void>;

export function TriggerCapture(arg1:string,arg2:number):Promise<string>;
