// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {admin} from '../models';

export function CheckPaymentStatus(arg1:string):Promise<boolean>;

export function GetCameraMode():Promise<string>;

export function GetDataDir():Promise<string>;

export function GetFrameConfig(arg1:string):Promise<main.FrontendFrameConfig>;

export function GetFrames():Promise<Array<admin.Frame>>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetLiveViewURL():Promise<string>;

export function GetWebcamID():Promise<string>;

export function IsPaymentBypassed():Promise<boolean>;

export function PrintPhoto(arg1:string):Promise<void>;

export function ProcessComposite(arg1:Array<string>,arg2:Array<boolean>,arg3:string,arg4:string):Promise<string>;

export function SaveWebRTCImage(arg1:string,arg2:number,arg3:string):Promise<string>;

export function SendEmail(arg1:string,arg2:string):Promise<void>;

export function SetAvailableCameras(arg1:Array<admin.CameraDevice>):Promise<void>;

export function StartLiveView():Promise<void>;

export function StopLiveView():Promise<void>;

export function TriggerCapture(arg1:string,arg2:number):Promise<string>;
