// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPaymentStatus(arg1) {
  return window['go']['main']['App']['CheckPaymentStatus'](arg1);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function PrintPhoto(arg1) {
  return window['go']['main']['App']['PrintPhoto'](arg1);
}

export function ProcessComposite(arg1, arg2) {
  return window['go']['main']['App']['ProcessComposite'](arg1, arg2);
}

export function TriggerCapture(arg1, arg2) {
  return window['go']['main']['App']['TriggerCapture'](arg1, arg2);
}
