// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPaymentStatus(arg1) {
  return window['go']['main']['App']['CheckPaymentStatus'](arg1);
}

export function GetCameraMode() {
  return window['go']['main']['App']['GetCameraMode']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetFrameConfig(arg1) {
  return window['go']['main']['App']['GetFrameConfig'](arg1);
}

export function GetFrames() {
  return window['go']['main']['App']['GetFrames']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetLiveViewURL() {
  return window['go']['main']['App']['GetLiveViewURL']();
}

export function GetWebcamID() {
  return window['go']['main']['App']['GetWebcamID']();
}

export function IsPaymentBypassed() {
  return window['go']['main']['App']['IsPaymentBypassed']();
}

export function PrintPhoto(arg1) {
  return window['go']['main']['App']['PrintPhoto'](arg1);
}

export function ProcessComposite(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessComposite'](arg1, arg2, arg3, arg4);
}

export function SaveWebRTCImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWebRTCImage'](arg1, arg2, arg3);
}

export function SendEmail(arg1, arg2) {
  return window['go']['main']['App']['SendEmail'](arg1, arg2);
}

export function SetAvailableCameras(arg1) {
  return window['go']['main']['App']['SetAvailableCameras'](arg1);
}

export function StartLiveView() {
  return window['go']['main']['App']['StartLiveView']();
}

export function StopLiveView() {
  return window['go']['main']['App']['StopLiveView']();
}

export function TriggerCapture(arg1, arg2) {
  return window['go']['main']['App']['TriggerCapture'](arg1, arg2);
}
